### ISSUE TITLE
收盘字段变了

### ISSUE THREAD

**Issue by github35** [CBJerry993/TT_Fund#1]
改了一下

# 1.指数每日涨跌幅
    def parse(self, response):
        response = re.findall(r'\((.*?)\);$', response.text)[0]
        response = json.loads(response)
        for i in response.get("data").get("klines"):
            item = {"code": response.get("data").get("code"), "name": response.get("data").get("name"),
                    "datetime": i.split(",")[0], "price_start": i.split(",")[1], "price_end": i.split(",")[2], "price_min": i.split(",")[4], "price_max": i.split(",")[3], "amount": i.split(",")[5], "value": i.split(",")[6],
                    "swing": i.split(",")[7]}
            print(item), save_item_in_csv(item, "market_index_{}.csv".format(str_now_day), self.title_num_1)
            self.title_num_1 = 1

**Comment by CBJerry993** [comment]
对的。我这边也改掉了。谢谢！
